# Generated by Django 5.0 on 2024-02-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='condition',
            field=models.IntegerField(verbose_name='Condition'),
        ),
    ]
