# Generated by Django 5.0 on 2024-03-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_alter_advert_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='condition',
            field=models.CharField(max_length=30, verbose_name='Condition'),
        ),
    ]
