# Generated by Django 5.0 on 2024-08-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_advertisementimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='seller',
        ),
    ]
