# Generated by Django 5.0 on 2024-08-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0006_advert_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementimage',
            name='image_data',
            field=models.ImageField(upload_to='advert_images/'),
        ),
    ]
