# Generated by Django 5.0 on 2024-08-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0007_alter_advertisementimage_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementimage',
            name='image_data',
            field=models.BinaryField(),
        ),
    ]
